name: Release
on:
  release:
    types: [published]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - id: release-vars
        name: Release Variables
        run: |
          
          TAG_NAME="${{ github.event.release.tag_name }}"
          CHART_NAME="${TAG_NAME%-*}"
          CHART_VERSION=$(echo $TAG_NAME | perl -pe '($_)=/([0-9]+([.][0-9]+)+)/')
          
          echo "CHART_NAME=$CHART_NAME" >> $GITHUB_OUTPUT
          echo "CHART_VERSION=$CHART_VERSION" >> $GITHUB_OUTPUT
          
          echo $TAG_NAME
          echo $CHART_NAME
          echo $CHART_VERSION
      
      - id: wait-published
        name: Wait Published
        run: |
          helm repo add misoboy https://misoboy.github.io/helm-charts
          
          CNT=0
          CHART_NAME=${{ steps.release-vars.outputs.CHART_NAME }}
          CHART_VERSION=${{ steps.release-vars.outputs.CHART_VERSION }}
          while [ $CNT == 0 ]; do helm repo update misoboy >> /dev/null; CNT=$(helm search repo misoboy/$CHART_NAME --version $CHART_VERSION -o json | jq length); sleep 1; done

      - uses: clowdhaus/argo-cd-action/@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: 2.5.5
          command: app patch ${{ steps.release-vars.outputs.CHART_NAME }}
          options: >
            --patch '{"spec": { "source": { "targetRevision": "${{ steps.release-vars.outputs.CHART_VERSION }}" }}}'
            --type merge
            --server ${{ secrets.ARGOCD_HOST }}
            --insecure
            --auth-token ${{ secrets.ARGOCD_TOKEN }}
